import './globals.css'
import { Inter } from 'next/font/google'
import SideBar from '../components/SideBar'
import SessionProvider from '../components/SessionProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from "../pages/api/auth/[...nextauth].js";
import Login from '@/components/Login'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">

      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ? 
              (<Login/>)
          :
         
          (<div className="flex">
             <div className=" bg-[#202123] min-w-[10rem] px-2 h-screen  md:min-w-[20rem]">
               <SideBar />
             </div>
             {/* notification bar */}
             <div> {children} </div>
           </div>)
          }
       
        </SessionProvider>
      </body>
    </html>
  )
}
